apiVersion: v1
kind: ConfigMap
metadata:
  name: bookstore-config
  namespace: bookstore
data:
  NODE_ENV: "production"
  RABBITMQ_URL: "amqp://rabbitmq-service:5672"
  RABBITMQ_HOST: "rabbitmq-service"
  RABBITMQ_PORT: "5672"
  CATALOG_SERVICE_URL: "http://catalog-service:5001"
  USER_SERVICE_URL: "http://user-service:5002"
---
apiVersion: v1
kind: Secret
metadata:
  name: bookstore-secrets
  namespace: bookstore
type: Opaque
stringData:
  MONGO_URI: "mongodb+srv://damian:Sammy6969*@cluster0.wvgjxy0.mongodb.net/bookstore"
  