apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: bookstore
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080  # Puerto que se expondr√° en los nodos
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: user-service-nodeport
  namespace: bookstore
spec:
  selector:
    app: user-service
  ports:
  - port: 5002
    targetPort: 5002
    nodePort: 30002  # Puerto para user-service
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service-nodeport
  namespace: bookstore
spec:
  selector:
    app: catalog-service
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001  # Puerto para catalog-service
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: cart-service-nodeport
  namespace: bookstore
spec:
  selector:
    app: cart-service
  ports:
  - port: 5004
    targetPort: 5004
    nodePort: 30004  # Puerto para cart-service
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service-nodeport
  namespace: bookstore
spec:
  selector:
    app: notification-service
  ports:
  - port: 5003
    targetPort: 5003
    nodePort: 30003  # Puerto para notification-service
  type: NodePort